/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.wigerlabs.tidetempo.dialog;

import com.wigerlabs.tidetempo.connection.MySQL;
import com.wigerlabs.tidetempo.util.SessionManager;
import com.wigerlabs.tidetempo.util.TopBarStyle;
import com.wigerlabs.tidetempo.util.User;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author malee
 */
public class ContractViewDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContractViewDialog.class.getName());

    private int contractId;
    private User userData;
    private static String beforeHtml = "<html><p style='width: 100%; word-wrap: break-word; white-space: normal;'>";
    private static String afterHtml = "</p></html>";

    /**
     * Creates new form ProjectView
     */
    public ContractViewDialog(java.awt.Frame parent, boolean modal, int contractId) {
        super(parent, modal);
        initComponents();
        loadUserSessionData();
        this.contractId = contractId;
        loadContractData();
        TopBarStyle.getInstance().applyStyle(this);
    }

    private void loadContractData() {
        try {
            ResultSet rs = MySQL.execute("SELECT c.id, c.date, pt.name AS project_template, cl.name AS client, p.title AS project_title, pa.name AS payment_schedule, "
                    + "c.total_amount, c.hourly_rate, c.estimated_hours, c.number_of_revisions, c.cancellation_policy, c.intellectual_policy, c.created_at, c.updated_at "
                    + "FROM contract c "
                    + "INNER JOIN project_template pt ON c.project_template_id = pt.id "
                    + "INNER JOIN client cl ON c.client_id = cl.id "
                    + "INNER JOIN project p ON c.project_id = p.id "
                    + "INNER JOIN payment_schedule pa ON c.payment_schedule_id = pa.id "
                    + "WHERE c.id='" + contractId + "' AND p.user_id='" + userData.id + "'");
            if (rs.next()) {
                String title = rs.getString("project_title");
                titleLabel.setText("Contract Details (" + title + ")");
                projectTitleLabel2.setText(beforeHtml + title + afterHtml);
                contractDateLabel2.setText(rs.getString("date"));
                projectTemplateLabel2.setText(rs.getString("project_template"));
                clientLabel2.setText(rs.getString("client"));
                paymentScheduleLabel2.setText(rs.getString("payment_schedule"));
                totalAmountLabel2.setText(rs.getString("total_amount"));
                hourlyRateLabel2.setText(rs.getString("hourly_rate"));
                estimatedHoursLabel2.setText(rs.getString("estimated_hours"));
                numberOfRevisionsLabel2.setText(rs.getString("number_of_revisions"));
                createdAtLabel2.setText(rs.getString("created_at"));
                updatedAtLabel2.setText(rs.getString("updated_at"));
                cancellationPolicyLabel2.setText(beforeHtml + rs.getString("cancellation_policy") + afterHtml);
                intellectualPolicyLabel2.setText(beforeHtml + rs.getString("intellectual_policy") + afterHtml);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void loadUserSessionData() {
        userData = SessionManager.getUserSession();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        projectTitleLabel1 = new javax.swing.JLabel();
        projectTitleLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        projectTemplateLabel1 = new javax.swing.JLabel();
        projectTemplateLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        clientLabel1 = new javax.swing.JLabel();
        clientLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        paymentScheduleLabel1 = new javax.swing.JLabel();
        paymentScheduleLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        totalAmountLabel1 = new javax.swing.JLabel();
        totalAmountLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        contractDateLabel1 = new javax.swing.JLabel();
        contractDateLabel2 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        hourlyRateLabel1 = new javax.swing.JLabel();
        hourlyRateLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        numberOfRevisionsLabel1 = new javax.swing.JLabel();
        numberOfRevisionsLabel2 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        createdAtLabel1 = new javax.swing.JLabel();
        createdAtLabel2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jPanel18 = new javax.swing.JPanel();
        estimatedHoursLabel1 = new javax.swing.JLabel();
        estimatedHoursLabel2 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jPanel19 = new javax.swing.JPanel();
        updatedAtLabel1 = new javax.swing.JLabel();
        updatedAtLabel2 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jPanel15 = new javax.swing.JPanel();
        cancellationPolicyLabel1 = new javax.swing.JLabel();
        cancellationPolicyLabel2 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        intellectualPolicyLabel1 = new javax.swing.JLabel();
        intellectualPolicyLabel2 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        titleLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel9.setBackground(new java.awt.Color(2, 8, 23));

        jPanel1.setOpaque(false);

        jPanel11.setMaximumSize(new java.awt.Dimension(884, 32767));
        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setMaximumSize(new java.awt.Dimension(442, 32767));
        jPanel2.setOpaque(false);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        projectTitleLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        projectTitleLabel1.setText("Project Title");
        jPanel3.add(projectTitleLabel1);

        projectTitleLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(projectTitleLabel2);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        projectTemplateLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        projectTemplateLabel1.setText("Project Template");
        jPanel5.add(projectTemplateLabel1);

        projectTemplateLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(projectTemplateLabel2);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        clientLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clientLabel1.setText("Client");
        jPanel6.add(clientLabel1);

        clientLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(clientLabel2);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        paymentScheduleLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        paymentScheduleLabel1.setText("Payment Schedule");
        jPanel7.add(paymentScheduleLabel1);

        paymentScheduleLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(paymentScheduleLabel2);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        totalAmountLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalAmountLabel1.setText("Total Amount");
        jPanel8.add(totalAmountLabel1);

        totalAmountLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.add(totalAmountLabel2);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.GridLayout(1, 2));

        contractDateLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        contractDateLabel1.setText("Contract Date");
        jPanel10.add(contractDateLabel1);

        contractDateLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(contractDateLabel2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addComponent(jSeparator5)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel11.add(jPanel2);

        jPanel12.setOpaque(false);

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new java.awt.GridLayout(1, 2));

        hourlyRateLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hourlyRateLabel1.setText("Hourly Rate");
        jPanel13.add(hourlyRateLabel1);

        hourlyRateLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.add(hourlyRateLabel2);

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new java.awt.GridLayout(1, 2));

        numberOfRevisionsLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numberOfRevisionsLabel1.setText("Number of Revisions");
        jPanel14.add(numberOfRevisionsLabel1);

        numberOfRevisionsLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel14.add(numberOfRevisionsLabel2);

        jPanel17.setOpaque(false);
        jPanel17.setPreferredSize(new java.awt.Dimension(64, 16));
        jPanel17.setLayout(new java.awt.GridLayout(1, 2));

        createdAtLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        createdAtLabel1.setText("Created At");
        jPanel17.add(createdAtLabel1);

        createdAtLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel17.add(createdAtLabel2);

        jPanel18.setOpaque(false);
        jPanel18.setLayout(new java.awt.GridLayout(1, 2));

        estimatedHoursLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        estimatedHoursLabel1.setText("Estimated Hours");
        jPanel18.add(estimatedHoursLabel1);

        estimatedHoursLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel18.add(estimatedHoursLabel2);

        jPanel19.setOpaque(false);
        jPanel19.setPreferredSize(new java.awt.Dimension(64, 16));
        jPanel19.setLayout(new java.awt.GridLayout(1, 2));

        updatedAtLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updatedAtLabel1.setText("Updated At");
        jPanel19.add(updatedAtLabel1);

        updatedAtLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel19.add(updatedAtLabel2);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator6)
            .addComponent(jSeparator9)
            .addComponent(jSeparator10)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
            .addComponent(jSeparator11)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator12)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel11.add(jPanel12);

        jPanel15.setOpaque(false);
        jPanel15.setLayout(new java.awt.GridLayout(1, 2));

        cancellationPolicyLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancellationPolicyLabel1.setText("Cancellation Policy");
        jPanel15.add(cancellationPolicyLabel1);

        cancellationPolicyLabel2.setForeground(new java.awt.Color(255, 255, 255));
        cancellationPolicyLabel2.setMaximumSize(new java.awt.Dimension(104, 32767));
        cancellationPolicyLabel2.setPreferredSize(new java.awt.Dimension(104, 32767));
        jPanel15.add(cancellationPolicyLabel2);

        jPanel16.setOpaque(false);
        jPanel16.setLayout(new java.awt.GridLayout(1, 2));

        intellectualPolicyLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        intellectualPolicyLabel1.setText("Intellectual Policy");
        jPanel16.add(intellectualPolicyLabel1);

        intellectualPolicyLabel2.setForeground(new java.awt.Color(255, 255, 255));
        intellectualPolicyLabel2.setMaximumSize(new java.awt.Dimension(104, 32767));
        intellectualPolicyLabel2.setPreferredSize(new java.awt.Dimension(104, 32767));
        jPanel16.add(intellectualPolicyLabel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setText("Contract Details");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancellationPolicyLabel1;
    private javax.swing.JLabel cancellationPolicyLabel2;
    private javax.swing.JLabel clientLabel1;
    private javax.swing.JLabel clientLabel2;
    private javax.swing.JLabel contractDateLabel1;
    private javax.swing.JLabel contractDateLabel2;
    private javax.swing.JLabel createdAtLabel1;
    private javax.swing.JLabel createdAtLabel2;
    private javax.swing.JLabel estimatedHoursLabel1;
    private javax.swing.JLabel estimatedHoursLabel2;
    private javax.swing.JLabel hourlyRateLabel1;
    private javax.swing.JLabel hourlyRateLabel2;
    private javax.swing.JLabel intellectualPolicyLabel1;
    private javax.swing.JLabel intellectualPolicyLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel numberOfRevisionsLabel1;
    private javax.swing.JLabel numberOfRevisionsLabel2;
    private javax.swing.JLabel paymentScheduleLabel1;
    private javax.swing.JLabel paymentScheduleLabel2;
    private javax.swing.JLabel projectTemplateLabel1;
    private javax.swing.JLabel projectTemplateLabel2;
    private javax.swing.JLabel projectTitleLabel1;
    private javax.swing.JLabel projectTitleLabel2;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel totalAmountLabel1;
    private javax.swing.JLabel totalAmountLabel2;
    private javax.swing.JLabel updatedAtLabel1;
    private javax.swing.JLabel updatedAtLabel2;
    // End of variables declaration//GEN-END:variables
}
