/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.wigerlabs.tidetempo.dialog;

import com.wigerlabs.tidetempo.connection.MySQL;
import com.wigerlabs.tidetempo.panel.TasksPanel;
import com.wigerlabs.tidetempo.util.CurrentTimeGenerator;
import com.wigerlabs.tidetempo.util.ComboItem;
import com.wigerlabs.tidetempo.util.SessionManager;
import com.wigerlabs.tidetempo.util.TopBarStyle;
import com.wigerlabs.tidetempo.util.User;
import com.wigerlabs.tidetempo.validation.Validator;
import java.util.List;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author malee
 */
public class TaskAddEditDialog extends javax.swing.JDialog {

    private List<ComboItem> projectList;
    private User userData;
    private boolean isEditing = false;
    private int taskId = 1;
    private TasksPanel tasksPanel;

    /**
     * Creates new form ProjectAddDialog
     *
     * @param parent
     * @param modal
     */
    public TaskAddEditDialog(java.awt.Frame parent, boolean modal, boolean isEditing, int taskId, TasksPanel tasksPanel) {
        super(parent, modal);
        initComponents();
        this.isEditing = isEditing;
        this.taskId = taskId;
        this.tasksPanel = tasksPanel;
        loadUserSessionData();
        loadProjects();
        init();
        TopBarStyle.getInstance().applyStyle(this);
    }

    public TaskAddEditDialog(java.awt.Frame parent, boolean modal, TasksPanel tasksPanel) {
        super(parent, modal);
        initComponents();
        this.tasksPanel = tasksPanel;
        loadUserSessionData();
        loadProjects();
        init();
        TopBarStyle.getInstance().applyStyle(this);
    }

    private void init() {
        if (isEditing) {
            headerLabel.setText("Edit Task Details");
            createButton.setText("Update Task");
            loadTaskData();
        } else {
            headerLabel.setText("Add Task Details");
            createButton.setText("Create Task");
        }
    }

    private void loadTaskData() {
        try {
            ResultSet rs = MySQL.execute("SELECT t.title, p.title AS project "
                    + "FROM task t "
                    + "INNER JOIN project p ON t.project_id = p.id "
                    + "WHERE t.id='" + taskId + "'");
            if (rs.next()) {
                titleField.setText(rs.getString("title"));

                for (ComboItem c: projectList) {
                    if(c.getName().equals(rs.getString("project"))) {
                        projectCombo.setSelectedItem(c);
                        break;
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void loadUserSessionData() {
        userData = SessionManager.getUserSession();
    }

    private void loadProjects() {
        projectList = new ArrayList<>();
        projectCombo.addItem(new ComboItem(0, "Select Project"));
        try {
            ResultSet rs = MySQL.execute("SELECT * FROM `project`");
            while (rs.next()) {
                int id = rs.getInt("id");
                String name = rs.getString("title");
                ComboItem project = new ComboItem(id, name);
                projectList.add(project);
                projectCombo.addItem(project);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        clientLabel = new javax.swing.JLabel();
        projectCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Project");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(2, 8, 23));

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setText("Add Task Details");

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titleLabel.setText("Task Title");

        createButton.setBackground(new java.awt.Color(59, 130, 246));
        createButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createButton.setText("Create Task");
        createButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        clientLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clientLabel.setText("Project");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel)
                            .addComponent(headerLabel)
                            .addComponent(titleField)
                            .addComponent(projectCombo, 0, 293, Short.MAX_VALUE)
                            .addComponent(clientLabel))))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(headerLabel)
                .addGap(28, 28, 28)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clientLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String task_title = titleField.getText();
        ComboItem project = (ComboItem) projectCombo.getSelectedItem();

        Timestamp nowTime = CurrentTimeGenerator.getInstance().getCurrentTime();

        if (!Validator.isInputFieldValid("Task Title", task_title)) {
            return;
        } else if (!Validator.isComboBoxValid("Project", project.getId())) {
            return;
        }

        try {
            if (!isEditing) {
                MySQL.execute("INSERT INTO `task` (title, project_id, status_id, created_at) VALUES "
                        + "('" + task_title + "','" + project.getId() + "','" + 1 + "','" + nowTime + "')");
                SuccessDialog.show("Task added successfully!");
            } else {
                MySQL.execute("UPDATE `task` "
                        + " SET title='" + task_title + "', project_id='" + project.getId() + "', updated_at='" + nowTime + "' WHERE id='" + taskId + "'");
                SuccessDialog.show("Task updated successfully!");
            }
            if (tasksPanel != null) {
                SwingUtilities.invokeLater(() -> {
                    tasksPanel.loadTasks();
                });
            }
            this.dispose();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Please try again to add the same task.", "Task adding failed!", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_createButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clientLabel;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<com.wigerlabs.tidetempo.util.ComboItem> projectCombo;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
