/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.wigerlabs.tidetempo.components.contracts;

import com.github.lgooddatepicker.components.DatePickerSettings;
import com.wigerlabs.tidetempo.panel.ContractsPanel;
import com.wigerlabs.tidetempo.util.Colors;
import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import com.github.lgooddatepicker.components.DatePicker;
import com.wigerlabs.tidetempo.connection.MySQL;
import com.wigerlabs.tidetempo.util.Client;
import com.wigerlabs.tidetempo.util.ComboItem;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author malee
 */
public class BasicInfoPanel extends javax.swing.JPanel {
    
    ContractsPanel parent;
    ArrayList<Client> clientList;
    ArrayList<ComboItem> projectTemplateList;

    /**
     * Creates new form BasicInfoPanel
     */
    public BasicInfoPanel(ContractsPanel parent) {
        initComponents();
        this.parent = parent;
        init();
        loadClients();
        loadProjectTemplate();
    }
    
    private void loadClients() {
        clientList = new ArrayList<>();
        clientCombo.addItem(new Client(0, "Select Client", ""));
        try {
            ResultSet rs = MySQL.execute("SELECT * FROM `client`");
            while (rs.next()) {
                int id = rs.getInt("id");
                String name = rs.getString("name");
                String email = rs.getString("email");
                Client client = new Client(id, name, email);
                clientList.add(client);
                clientCombo.addItem(client);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void loadProjectTemplate() {
        projectTemplateList = new ArrayList<>();
        projectTemplateCombo.addItem(new ComboItem(0, "Select a Template"));
        try {
            ResultSet rs = MySQL.execute("SELECT * FROM `project_template`");
            while (rs.next()) {
                int id = rs.getInt("id");
                String name = rs.getString("name");
                ComboItem template = new ComboItem(id, name);
                projectTemplateList.add(template);
                projectTemplateCombo.addItem(template);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void init() {
        DatePickerSettings settings = new DatePickerSettings();
        settings.setColor(DatePickerSettings.DateArea.BackgroundTodayLabel, Colors.DARK_BLUE);
        settings.setColor(DatePickerSettings.DateArea.BackgroundClearLabel, Colors.DARK_BLUE);
        settings.setColor(DatePickerSettings.DateArea.BackgroundMonthAndYearMenuLabels, Colors.DARK_BLUE);
        settings.setColor(DatePickerSettings.DateArea.BackgroundOverallCalendarPanel, Colors.DARK_BLUE);
        settings.setColor(DatePickerSettings.DateArea.BackgroundMonthAndYearNavigationButtons, Colors.LIGHT_BLUE);
        settings.setColor(DatePickerSettings.DateArea.CalendarTextWeekdays, Color.WHITE);
        settings.setColor(DatePickerSettings.DateArea.CalendarBackgroundNormalDates, Colors.DARK_BLUE);
        settings.setColor(DatePickerSettings.DateArea.CalendarTextNormalDates, Color.WHITE);
        settings.setColor(DatePickerSettings.DateArea.CalendarBackgroundSelectedDate, Colors.BUTTON_BLUE);
        settings.setColor(DatePickerSettings.DateArea.DatePickerTextValidDate, Color.WHITE);
        settings.setColor(DatePickerSettings.DateArea.TextFieldBackgroundValidDate, new Color(40,40,40));
        settings.setColor(DatePickerSettings.DateArea.TextFieldBackgroundInvalidDate, Color.RED);
        settings.setColor(DatePickerSettings.DateArea.DatePickerTextInvalidDate, Color.WHITE);
        settings.setColorBackgroundWeekdayLabels(Colors.LIGHT_BLUE, true);
        settings.setColor(DatePickerSettings.DateArea.BackgroundCalendarPanelLabelsOnHover, Colors.DARK_BLUE);
        contractDatePicker.setSettings(settings);
    }
    
    public JComboBox getClientCombo() {
        return clientCombo;
    }
    
    public DatePicker getContractDatePicker() {
        return contractDatePicker;
    }
    
    public JComboBox getProjectTemplate() {
        return projectTemplateCombo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basicInfoPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        clientCombo = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        contractDatePicker = new com.github.lgooddatepicker.components.DatePicker();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        projectTemplateCombo = new javax.swing.JComboBox<>();
        nextBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(2, 8, 23));

        basicInfoPanel.setOpaque(false);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(2, 2));

        jPanel4.setOpaque(false);

        jLabel2.setText("Client *");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        clientCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(215, 215, 215))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(clientCombo, 0, 317, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel4);

        jPanel6.setOpaque(false);

        jLabel4.setText("Contract Date");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        contractDatePicker.setOpaque(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contractDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contractDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6);

        jPanel7.setOpaque(false);

        jLabel5.setText("Project Template");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        projectTemplateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectTemplateComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addContainerGap(221, Short.MAX_VALUE))
            .addComponent(projectTemplateCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectTemplateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel7);

        nextBtn.setText("Next");
        nextBtn.setBackground(new java.awt.Color(59, 130, 246));
        nextBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        nextBtn.setIconTextGap(10);
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Basic Info");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        javax.swing.GroupLayout basicInfoPanelLayout = new javax.swing.GroupLayout(basicInfoPanel);
        basicInfoPanel.setLayout(basicInfoPanelLayout);
        basicInfoPanelLayout.setHorizontalGroup(
            basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(basicInfoPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basicInfoPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        basicInfoPanelLayout.setVerticalGroup(
            basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basicInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basicInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        parent.contentPanelLayout.show(parent.getContentPanel(), "project_details_panel");
    }//GEN-LAST:event_nextBtnActionPerformed

    private void projectTemplateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectTemplateComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectTemplateComboActionPerformed

    private void clientComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basicInfoPanel;
    private javax.swing.JComboBox<com.wigerlabs.tidetempo.util.Client> clientCombo;
    private com.github.lgooddatepicker.components.DatePicker contractDatePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton nextBtn;
    private javax.swing.JComboBox<com.wigerlabs.tidetempo.util.ComboItem> projectTemplateCombo;
    // End of variables declaration//GEN-END:variables
}
