/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.wigerlabs.tidetempo.gui;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.wigerlabs.tidetempo.panel.LoginPanel;
import com.wigerlabs.tidetempo.panel.RegisterPanel;
import com.wigerlabs.tidetempo.util.SessionManager;
import com.wigerlabs.tidetempo.util.TopBarStyle;
import com.wigerlabs.tidetempo.util.User;
import java.awt.CardLayout;
import javax.swing.SwingUtilities;

/**
 *
 * @author malee
 */
public class AuthScreen extends javax.swing.JFrame {

    private static AuthScreen instance;
    private HomeScreen homeScreen;

    private CardLayout authContentPanelLayout;
    private RegisterPanel registerPanel;
    private LoginPanel loginPanel;

    public void displayRegisterPanel() {
        this.authContentPanelLayout.show(authContentPanel, "register_panel");
    }

    public void displayLoginPanel() {
        this.authContentPanelLayout.show(authContentPanel, "login_panel");
    }

    /**
     * Creates new form LoginScreen
     */
    private AuthScreen() {
        initComponents();
        homeScreen = HomeScreen.getInstance();
        loadPanels();
        SwingUtilities.invokeLater(this::checkIfUserLoggedIn);
        TopBarStyle.getInstance().applyStyle(this);
    }
    
    public static AuthScreen getInstance() {
        System.out.println(instance == null);
        if(instance == null) {
            System.out.println("assigning");
            instance = new AuthScreen();
        }
        System.out.println(instance);
        return instance;
    }

    private synchronized void checkIfUserLoggedIn() {
        User userData = SessionManager.getUserSession();
        if (userData != null) {
            if (userData.name != null || userData.email != null || userData.password != null) {
                homeScreen.setVisible(true);
                this.dispose();
            }
        }
    }

    private void loadPanels() {
        if (authContentPanelLayout == null && authContentPanel.getLayout() instanceof CardLayout) {
            this.authContentPanelLayout = (CardLayout) authContentPanel.getLayout();
        }
        this.registerPanel = new RegisterPanel(this);
        this.loginPanel = new LoginPanel(this);
        authContentPanel.add(this.loginPanel, "login_panel");
        authContentPanel.add(this.registerPanel, "register_panel");

        SwingUtilities.updateComponentTreeUI(authContentPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authContentPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Screen");
        setBackground(new java.awt.Color(255, 255, 255));

        authContentPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wigerlabs/tidetempo/img/login_background.jpg"))); // NOI18N
        jLabel1.setMinimumSize(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(authContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(authContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMacDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> AuthScreen.getInstance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel authContentPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
