/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.wigerlabs.tidetempo.gui;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.wigerlabs.tidetempo.panel.ClientsPanel;
import com.wigerlabs.tidetempo.panel.ContractsPanel;
import com.wigerlabs.tidetempo.panel.DashboardPanel;
import com.wigerlabs.tidetempo.panel.ProjectsPanel;
import com.wigerlabs.tidetempo.panel.SettingsPanel;
import com.wigerlabs.tidetempo.panel.StartWorkingPanel;
import com.wigerlabs.tidetempo.panel.TasksPanel;
import com.wigerlabs.tidetempo.util.Colors;
import com.wigerlabs.tidetempo.util.SessionManager;
import com.wigerlabs.tidetempo.util.TopBarStyle;
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.SwingUtilities;

/**
 *
 * @author malee
 */
public class HomeScreen extends javax.swing.JFrame {

    private CardLayout contentPanelLayout;
    
    private DashboardPanel dashboardPanel;
    private ClientsPanel clientsPanel;
    private ProjectsPanel projectsPanel;
    private TasksPanel tasksPanel;
    private StartWorkingPanel startWorkingPanel;
    private ContractsPanel contractsPanel;
    private SettingsPanel settingsPanel;

    /**
     * Creates new form Home
     */
    public HomeScreen() {
        initComponents();
        init();
        loadPanels();
    }

    private void init() {
        TopBarStyle.getInstance().applyStyle(this);
        dashboardBtn.setIcon(new FlatSVGIcon("com/wigerlabs/tidetempo/img/dashboard_icon.svg", 30, 30));
        clientsBtn.setIcon(new FlatSVGIcon("com/wigerlabs/tidetempo/img/users_icon.svg", 25, 25));
        projectsBtn.setIcon(new FlatSVGIcon("com/wigerlabs/tidetempo/img/projects_icon.svg", 25, 25));
        tasksBtn.setIcon(new FlatSVGIcon("com/wigerlabs/tidetempo/img/check_icon.svg", 25, 25));
        startWorkingBtn.setIcon(new FlatSVGIcon("com/wigerlabs/tidetempo/img/clock_icon.svg", 25, 25));
        contractsBtn.setIcon(new FlatSVGIcon("com/wigerlabs/tidetempo/img/file_icon.svg", 25, 25));
        settingsBtn.setIcon(new FlatSVGIcon("com/wigerlabs/tidetempo/img/settings_icon.svg", 25, 25));
        logoutBtn.setIcon(new ImageIcon(getClass().getResource("/com/wigerlabs/tidetempo/img/logout_icon.png")));
    }
    
    private void setButtonActive(JButton button) {
        dashboardBtn.setBackground(Colors.SIDEBAR_BLUE);
        clientsBtn.setBackground(Colors.SIDEBAR_BLUE);
        projectsBtn.setBackground(Colors.SIDEBAR_BLUE);
        tasksBtn.setBackground(Colors.SIDEBAR_BLUE);
        startWorkingBtn.setBackground(Colors.SIDEBAR_BLUE);
        contractsBtn.setBackground(Colors.SIDEBAR_BLUE);
        settingsBtn.setBackground(Colors.DARK_BLUE);
        button.setBackground(Colors.BUTTON_BLUE);
    }

    private void loadPanels() {
        if (contentPanelLayout == null && contentPanel.getLayout() instanceof CardLayout) {
            this.contentPanelLayout = (CardLayout) contentPanel.getLayout();
        }
        this.dashboardPanel = new DashboardPanel(this);
        this.clientsPanel = new ClientsPanel(this);
        this.projectsPanel = new ProjectsPanel(this);
        this.tasksPanel = new TasksPanel(this);
        this.startWorkingPanel = new StartWorkingPanel();
        this.contractsPanel = new ContractsPanel(this);
        this.settingsPanel = new SettingsPanel(this);
        contentPanel.add(this.dashboardPanel, "dashboard_panel");
        contentPanel.add(this.clientsPanel, "clients_panel");
        contentPanel.add(this.projectsPanel, "projects_panel");
        contentPanel.add(this.tasksPanel, "tasks_panel");
        contentPanel.add(this.startWorkingPanel, "start_working_panel");
        contentPanel.add(this.contractsPanel, "contracts_panel");
        contentPanel.add(this.settingsPanel, "settings_panel");
        SwingUtilities.updateComponentTreeUI(contentPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        settingsBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        tasksBtn = new javax.swing.JButton();
        projectsBtn = new javax.swing.JButton();
        clientsBtn = new javax.swing.JButton();
        startWorkingBtn = new javax.swing.JButton();
        dashboardBtn = new javax.swing.JButton();
        contractsBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(2, 8, 23));

        jPanel2.setBackground(new java.awt.Color(7, 15, 32));

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wigerlabs/tidetempo/img/logo.png"))); // NOI18N
        logoLabel.setMinimumSize(new java.awt.Dimension(268, 58));
        logoLabel.setPreferredSize(new java.awt.Dimension(268, 58));

        logoutBtn.setBackground(new java.awt.Color(102, 0, 0));
        logoutBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logoutBtn.setIconTextGap(10);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        settingsBtn.setBackground(new java.awt.Color(2, 8, 23));
        settingsBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        settingsBtn.setText("Settings");
        settingsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        settingsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        settingsBtn.setIconTextGap(10);
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });

        jPanel3.setOpaque(false);

        tasksBtn.setBackground(new java.awt.Color(7, 15, 32));
        tasksBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        tasksBtn.setText("Tasks");
        tasksBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tasksBtn.setIconTextGap(10);
        tasksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasksBtnActionPerformed(evt);
            }
        });

        projectsBtn.setBackground(new java.awt.Color(7, 15, 32));
        projectsBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        projectsBtn.setText("Projects");
        projectsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        projectsBtn.setIconTextGap(10);
        projectsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectsBtnActionPerformed(evt);
            }
        });

        clientsBtn.setBackground(new java.awt.Color(7, 15, 32));
        clientsBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        clientsBtn.setText("Clients");
        clientsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clientsBtn.setIconTextGap(10);
        clientsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsBtnActionPerformed(evt);
            }
        });

        startWorkingBtn.setBackground(new java.awt.Color(7, 15, 32));
        startWorkingBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        startWorkingBtn.setText("Start Working");
        startWorkingBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        startWorkingBtn.setIconTextGap(10);
        startWorkingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startWorkingBtnActionPerformed(evt);
            }
        });

        dashboardBtn.setBackground(new java.awt.Color(59, 130, 246));
        dashboardBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        dashboardBtn.setText("Dashboard");
        dashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboardBtn.setIconTextGap(10);
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });

        contractsBtn.setBackground(new java.awt.Color(7, 15, 32));
        contractsBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        contractsBtn.setText("Contracts");
        contractsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        contractsBtn.setIconTextGap(10);
        contractsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contractsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(projectsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tasksBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(startWorkingBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
            .addComponent(clientsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dashboardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contractsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tasksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startWorkingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contractsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settingsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(settingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jScrollPane1.setBorder(null);

        contentPanel.setMinimumSize(new java.awt.Dimension(708, 588));
        contentPanel.setOpaque(false);
        contentPanel.setLayout(new java.awt.CardLayout());
        jScrollPane1.setViewportView(contentPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tasksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasksBtnActionPerformed
        this.contentPanelLayout.show(contentPanel, "tasks_panel");
        setButtonActive(tasksBtn);
    }//GEN-LAST:event_tasksBtnActionPerformed

    private void projectsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectsBtnActionPerformed
        this.contentPanelLayout.show(contentPanel, "projects_panel");
        setButtonActive(projectsBtn);
    }//GEN-LAST:event_projectsBtnActionPerformed

    private void startWorkingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startWorkingBtnActionPerformed
        this.contentPanelLayout.show(contentPanel, "start_working_panel");
        setButtonActive(startWorkingBtn);
    }//GEN-LAST:event_startWorkingBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        SessionManager.clearUserSession();
        AuthScreen authScreen = new AuthScreen();
        authScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void clientsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientsBtnActionPerformed
        this.contentPanelLayout.show(contentPanel, "clients_panel");
        setButtonActive(clientsBtn);
    }//GEN-LAST:event_clientsBtnActionPerformed

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        this.contentPanelLayout.show(contentPanel, "settings_panel");
        setButtonActive(settingsBtn);
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        this.contentPanelLayout.show(contentPanel, "dashboard_panel");
        setButtonActive(dashboardBtn);
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void contractsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contractsBtnActionPerformed
        this.contentPanelLayout.show(contentPanel, "contracts_panel");
        setButtonActive(contractsBtn);
    }//GEN-LAST:event_contractsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMacDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clientsBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton contractsBtn;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton projectsBtn;
    private javax.swing.JButton settingsBtn;
    private javax.swing.JButton startWorkingBtn;
    private javax.swing.JButton tasksBtn;
    // End of variables declaration//GEN-END:variables
}
