/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.wigerlabs.tidetempo.components.dashboard;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.wigerlabs.tidetempo.util.Colors;
import java.awt.Color;

/**
 *
 * @author malee
 */
public class ActiveProject extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public ActiveProject() {
        initComponents();
        init();
    }

    private void init() {
        statusBtn.setBackground(Colors.GREEN);
        statusBtn.putClientProperty(FlatClientProperties.STYLE, "arc: 99");
        dayCountLabel.setIcon(new FlatSVGIcon("com/wigerlabs/tidetempo/img/calendar.svg", 15, 15));
        companyNameLabel.setIcon(new FlatSVGIcon("com/wigerlabs/tidetempo/img/users_icon.svg", 15, 15));
    }
    
    public void setData(String title, String client, String statusStr, int progress, String daysLeft, String earnings, String hoursSpentAndTotal, boolean isLate) {
        jLabel1.setText(title);
        companyNameLabel.setText(client);
        statusBtn.setText(statusStr);
        jProgressBar1.setValue(progress);
        jLabel3.setText(progress + "%");
        dayCountLabel.setText(daysLeft);
        dayCountLabel1.setText(earnings);
        dayCountLabel2.setText(hoursSpentAndTotal);

        if (isLate) {
            dayCountLabel.setForeground(Color.RED);
        } else {
            dayCountLabel.setForeground(new Color(0, 153, 0));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        companyNameLabel = new javax.swing.JLabel();
        statusBtn = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dayCountLabel = new javax.swing.JLabel();
        dayCountLabel1 = new javax.swing.JLabel();
        dayCountLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(2, 8, 23));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        setMaximumSize(new java.awt.Dimension(32767, 150));

        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ecommerce Web Design");

        companyNameLabel.setText("TechCorp Inc");

        statusBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        statusBtn.setText("Active");

        jProgressBar1.setValue(80);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Progress");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("80%");

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        dayCountLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dayCountLabel.setForeground(new java.awt.Color(204, 0, 0));
        dayCountLabel.setText("3 days");
        jPanel2.add(dayCountLabel);

        dayCountLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dayCountLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayCountLabel1.setText("4,750 LKR");
        jPanel2.add(dayCountLabel1);

        dayCountLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dayCountLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dayCountLabel2.setText("28h/30h");
        jPanel2.add(dayCountLabel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(companyNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(statusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(companyNameLabel))
                    .addComponent(statusBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JLabel dayCountLabel;
    private javax.swing.JLabel dayCountLabel1;
    private javax.swing.JLabel dayCountLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton statusBtn;
    // End of variables declaration//GEN-END:variables
}
